id: P3207A2B1
initial_creation_type: ocr
source_metadata:
  volumes:
    1bc79f0be94e4ebcb2994f28675b4633:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: དཔལ་གསང་བ་འདུས་པའི་རྫོགས་རིམ་མཐར་ཕྱིན་པ།
      total_pages: 1634
      volume_number: 18
